CREATE TABLE IF NOT EXISTS Genre
(
    genre_id INTEGER primary key,
    genre    VARCHAR
);

CREATE TABLE IF NOT EXISTS mpa_rating
(
    mpa_rating_id INTEGER PRIMARY KEY,
    rating_value   VARCHAR
);

CREATE TABLE IF NOT EXISTS Film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  TEXT,
    release_date DATE,
    duration     LONG,
    mpa_rating  INTEGER REFERENCES mpa_rating (mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS Film_genre
(
    film_id  INTEGER REFERENCES Film (id),
    genre_id INTEGER REFERENCES Genre (genre_id)
);

CREATE TABLE IF NOT EXISTS User
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR NOT NULL,
    login        VARCHAR NOT NULL,
    name         VARCHAR NOT NULL,
    birthday     DATE
);

CREATE TABLE IF NOT EXISTS Friend
(
    first_user_id  INTEGER REFERENCES User (id),
    second_user_id INTEGER REFERENCES User (id),
    status         BOOLEAN
);

CREATE TABLE IF NOT EXISTS Likes
(
    film_id INTEGER REFERENCES Film (id),
    user_id INTEGER REFERENCES User (id)
);

/*Жанры*/
INSERT INTO Genre VALUES (1, 'COMEDY');
INSERT INTO Genre VALUES (2, 'DRAMA');
INSERT INTO Genre VALUES (3, 'CARTOON');
INSERT INTO Genre VALUES (4, 'THRILLER');
INSERT INTO Genre VALUES (5, 'DOCUMENTARY');
INSERT INTO Genre VALUES (6, 'ACTION');

/*MPA*/
INSERT INTO mpa_rating VALUES (1, 'G');
INSERT INTO mpa_rating VALUES (2, 'PG');
INSERT INTO mpa_rating VALUES (3, 'PG13');
INSERT INTO mpa_rating VALUES (4, 'R');
INSERT INTO mpa_rating VALUES (5, 'NC17');