/*Жанры*/
INSERT INTO Genre VALUES (1, 'COMEDY');
INSERT INTO Genre VALUES (2, 'DRAMA');
INSERT INTO Genre VALUES (3, 'Cartoon');
INSERT INTO Genre VALUES (4, 'THRILLER');
INSERT INTO Genre VALUES (5, 'DOCUMENTARY');
INSERT INTO Genre VALUES (6, 'ACTION MOVIE');

/*MPA*/
INSERT INTO mpa_rating VALUES (1, 'G');
INSERT INTO mpa_rating VALUES (2, 'PG');
INSERT INTO mpa_rating VALUES (3, 'PG13');
INSERT INTO mpa_rating VALUES (4, 'R');
INSERT INTO mpa_rating VALUES (5, 'NC17');