name: Films API Tests

on:
  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install newman
        run: |
          npm install -g newman
      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      - name: Run Application
        run: nohup mvn spring-boot:run &
      - run: /tmp/wait-for-it.sh -t 120 localhost:8080 -- echo "application is up"

      - name: Test API POSTMAN
        run: |
          newman run ./postman/sprint1.json -r cli
